### ISSUE TITLE
Clips still getting stuck in processing

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#2]
Clips get stuck in "still processing" and never come out.

**Device**:  That was on Chrome 83.0, Samsung Galaxy S20+ 5G

![Screen Shot 2020-07-17 at 10 48 49 AM](https://user-images.githubusercontent.com/6118115/88181461-de4ce580-cbfc-11ea-9de5-363e771cfd54.png)
![Screen Shot 2020-06-24 at 1 10 04 PM](https://user-images.githubusercontent.com/6118115/88181496-ee64c500-cbfc-11ea-995e-445ceaca4c7d.png)

**Comment by jmnolasco** [comment]
I noticed this today too! However, it did let me delete them if I click on the pencil icon. -iPhone XR, Safari browser

**Comment by jkhartshorne** [comment]
@jmnolasco - yes, I can delete them. But it's pretty frustrating to have just recorded something good with my distractible daughter to only have to end up deleting it.

**Comment by ythuang123** [comment]
This was an issue for me too. First time I've encountered it, I was using the regular KidTalk app (kidtalk.app) on my iPhone SE (version iOS 13.5.1) on Safari (latest?). Here are the pictures. It wasn't a particularly long recording (a couple minutes). I got the "uploaded complete" message but when the I went to the scrapbook, the tile was grayed out.

![2020-08-01_20-50-16_000](https://user-images.githubusercontent.com/68764650/89192253-20b5e100-d572-11ea-94f1-be844f05784b.png)
![2020-08-01_20-50-05_000](https://user-images.githubusercontent.com/68764650/89192260-23183b00-d572-11ea-84f3-189850ff62e1.png)

**Comment by ythuang123** [comment]
I've encountered the same error again -- see below. I was using the regular KidTalk app (kidtalk.app) on my iPhone SE (version iOS 13.5.1) on Safari (latest?). Here are the pictures. Same deal as before. It wasn't a particularly long recording (a couple minutes). I got the "uploaded complete" message but when the I went to the scrapbook, the tile was grayed out. 

This is a serious bug. Multiple times in one week. KidTalk enables parents to make a scrapbook of their child's speech, and if we can't guarantee that their recordings are saved, then this is a pretty serious breach of trust. What's being done to address this?

![2020-08-05_20-53-42_000](https://user-images.githubusercontent.com/68764650/89541568-8bfaef80-d7cc-11ea-9948-4360d87397de.png)
![2020-08-05_21-59-29_000](https://user-images.githubusercontent.com/68764650/89541576-8dc4b300-d7cc-11ea-8dfc-92ad4d8de456.png)

**Comment by lorenachipstudio** [comment]
@ythuang123 I've alerted Alex about this as high priority- I'll provide an update ASAP on this.

**Comment by lorenachipstudio** [comment]
@ythuang123 I spoke with Alex and we'll be deploying the fix into production today. The fixes were deployed into the staging site back on 7/24 and we were just awaiting confirmation from your team that this was fixed (in the staging site) before promoting it to production. 

We'll go ahead and promote it to production today so this should be resolved by tonight. 

Going forward, we'll just reply to each issue confirming that the fix is in staging and asking whomever reported the issue to confirm that it has been fixed, before we promote it to production. For this particular issue, I updated you and Josh via email because it had originally come through the Google Doc, so I believe it was just a misunderstanding. 

Let me know if you have any questions. 
Lorena

**Comment by ythuang123** [comment]
Got it, thanks a bunch. I really appreciate how quickly you guys were able to tackle this, and I'm sorry about the confusion about where the fixes lived. Your plan moving forward sounds good. 

Follow up questions--> What does it mean to "fix bug"? I'm on the kidtalk.app site (public one) and the two recordings are "still processing." Does that mean that these recordings are lost? So the only way to get rid of these blank tiles is to delete them? Or are there (hopefully) ways to recover them -- since they were uploaded? I'm asking to get a sense of how much data we've potentially lost and what we'd need to tell KidTalk research participants. Thanks!

**Comment by koppen152** [comment]
I have not encountered this issue in staging this week. Thanks! IPhone 7/safari/iOS 13.6

**Comment by ythuang123** [comment]
@lorenachipstudio -- I've encountered this issue on the Kidtalk.app site again (see below). I've been making a recording _everyday_ with my daughter to kick the tires on the live platform (experience what our research participants experience). These recordings are longer than our earlier ones (5-10 minutes), and this may be why we're encountering this bug now. So we've lost 3 of the last 11 recordings (27%) to this bug. This is pretty massive data loss. Can you provide more info about what the fix is? Thanks!

![2020-08-09_21-09-46_000](https://user-images.githubusercontent.com/68764650/89788335-fc678080-daec-11ea-88ba-9d73ff98eece.png)
![2020-08-09_21-09-55_000](https://user-images.githubusercontent.com/68764650/89788341-fd98ad80-daec-11ea-841d-536f95067973.png)

**Comment by ichimura-a** [comment]
I have also not encountered this issue in staging this past week. MacBook Air/Chrome 84.0.4147.105/macOS 10.15.6

**Comment by parkerrobbins** [comment]
I have also not observed this issue: 

Galaxy S9 | Android 10 | Chrome 84.0.4147.115
Dell Latitude E7450 | Ubuntu 18.04.4 LTS | Chrome 84.0.4147.105

**Comment by jkhartshorne** [comment]
Sounds like it isn't happening in staging. @lorenachipstudio - can you please answer Yi Ting's question above?

**Comment by alexchippendale** [comment]
@ythuang123 
That's frustrating, we're trying to get a better sense of what's going on in this case. We deployed a fix to an issue we found that causes the "still processing" to stay there and deployed on Thursday to production, but there may be a separate error getting thrown in your account. We have a few questions which will hopefully help us diagnose and fix this issue:

1) Could you check your older recordings that were made prior to the code we pushed to production on Thursday? The ones that were stuck before, are they still stuck? or is it only on the newer, longer recordings submitted since then?

2) Just to make sure, longer clips can take longer to process and if you go to the scrapbook right after making a longer recording it's possible it could take a little while. You're saying that these have stayed in processing for days correct? (Not that it said "still processing" right when you went to the scrapbook but cleared up eventually)

3) If possible, could you open the app in google chrome on a computer and see if you're seeing the same thing (especially after clearing cache)? If you're on an Apple laptop with chrome open on the scrapbook and are still seeing the grayed out "still processing" issue, try pressing and holding Command -> Option -> J for a second to open the developer console and take a screenshot of what it says in the console. We deployed a fix for an issue we found that can cause the "still processing" issue, and we want to see if it is the same one or something different.

It also might help to test a few longer recordings in staging to see if you get the same issue there. Staging and production should both have that fix from last week deployed. We'll want to see if one of other newer fixes that's been pushed to staging is why other users are not seeing the same issue on staging.

Thank you!

**Comment by ythuang123** [comment]
Thanks for your questions -- answers below! 

_> 1. Could you check your older recordings that were made prior to the code we pushed to production on Thursday? The ones that were stuck before, are they still stuck? or is it only on the newer, longer recordings submitted since then?_

The older and newer ones are all stuck. :(

_> Just to make sure, longer clips can take longer to process and if you go to the scrapbook right after making a longer recording it's possible it could take a little while. You're saying that these have stayed in processing for days correct? (Not that it said "still processing" right when you went to the scrapbook but cleared up eventually)_

Nah, I know what you're talking about but it's not that issue. It's been stuck for several days. 

_> If possible, could you open the app in google chrome on a computer and see if you're seeing the same thing (especially after clearing cache)? If you're on an Apple laptop with chrome open on the scrapbook and are still seeing the grayed out "still processing" issue, try pressing and holding Command -> Option -> J for a second to open the developer console and take a screenshot of what it says in the console. We deployed a fix for an issue we found that can cause the "still processing" issue, and we want to see if it is the same one or something different._

It's still an issue on my PC on Chrome (see below -- grayed out icons).

![image](https://user-images.githubusercontent.com/68764650/89830001-81708b00-db29-11ea-9cdc-adecfbf69a5d.png)

**Comment by alexchippendale** [comment]
@ythuang123 Thank you for your answers! This will help us narrow down what's going on. By the way, have you experienced this on staging at all or with other accounts?

**Comment by ythuang123** [comment]
@alexchippendale -- This is with the production site (kidtalk.app). I haven't encountered it in staging, but those clips have been much shorter.

**Comment by alexchippendale** [comment]
@ythuang123 Thanks for the info. We are working on this right now.

**Comment by ythuang123** [comment]
I've replicated the error on the staging.kidtalk.app site on my iPhone SE (version iOS 13.5.1) on Safari (latest?). It's a 10 minute clip and it's been grayed out for the last 20 minutes (logged in and out) -- see below. There's no "still processing" message on the staging site. I'm checking to see if I can get the error when recording from my PC laptop. 

![2020-08-10_18-14-48_000](https://user-images.githubusercontent.com/68764650/89836970-f21da480-db35-11ea-9cfd-f44745fd8f31.png)

**Comment by SecondStreetDevelopment** [comment]
@ythuang123 We've identified the error related to the issue with this recording.  We're researching it now.
![image](https://user-images.githubusercontent.com/49379014/89838652-a44a7180-db20-11ea-92eb-050fc24643ff.png)

**Comment by ythuang123** [comment]
I've replicated the error on the staging.kidtalk.app site on my Chrome, Window 10 Enterprise v. 1909 (OS build 18563.959), ThinkPad X1 Carbon 4G. It's a 24 minute clip and it's been grayed out for the last 15 minutes (logged in and out) -- see below. There's no "still processing" message on the staging site. 
![image](https://user-images.githubusercontent.com/68764650/89845942-dfaf6500-db4d-11ea-848d-c534427518ca.png)

**Comment by SecondStreetDevelopment** [comment]
@ythuang123 Thank you for the feedback.  Yes, it looks like this issue is related to the clip size so it will occur on any platform.  I'm working on a fix right now, I will let you know when we have it ready for staging.

**Comment by alexchippendale** [comment]
@ythuang123 We're continuing to work on this, will let you know when we have an update.

**Comment by SecondStreetDevelopment** [comment]
I've been able to reproduce this issue with a 12min clip.
![image](https://user-images.githubusercontent.com/49379014/90077374-d1c92380-dcb6-11ea-8faf-1ff50e1ad08c.png)

**Comment by lorenachipstudio** [comment]
@jkhartshorne Thank you for the additional info on this- I'll share this with Alex and the team as they continue to work on a fix.

**Comment by parkerrobbins** [comment]
@lorenachipstudio @jkhartshorne 

I also saw this in staging today for both the original clip I mentioned in #25 and for the other one I commented about in that issue today. (I somehow missed this the other day.)

Dell Latitude E7450 | Ubuntu 18.04.4 LTS | Chrome 84.0.4147.105

**Comment by ichimura-a** [comment]
I also saw this in staging whenever I tried adding a clip from "Import Audio from Video" into the scrapbook.

iPhone 7 / Safari / iOS 13.6

**Comment by SecondStreetDevelopment** [comment]
@ichimura-a, yes, thank you.  I have seen it in "Import Audio from Video" as well.  That is what I am working on right now.

**Comment by SecondStreetDevelopment** [comment]
I've just published a pull request which contains a fix for this issue.  We will let you know after it is reviewed and merged/published to the staging site.

**Comment by alexchippendale** [comment]
@ythuang123 We've deployed a fix for this issue to the staging site that should fix the problem for new recordings (thanks @SecondStreetDevelopment!). We are working on getting the older recordings "unstuck" if possible, but the deployed fix should prevent new recordings going forward from hitting this error and getting stuck in the scrapbook. Could you test staging with similar types of recordings that were getting stuck in your previous testing, and verify that new recordings go through without getting stuck? If that looks good, we'll work on promoting the fix to production as well. Thanks!

**Comment by ythuang123** [comment]
Thanks @alexchippendale and @SecondStreetDevelopment. I've created several clip on the staging site ranging from 7-23 minutes on my iPhone SE (safari) and Lenovo PC (chrome). Observations:

1. All recordings have posted! None of them have gotten stuck. Woo-hoo! 
2. The "converting" time on the PC/Chrome takes forever. Basically as long as the recording itself. So if I made a 11-min recording, I'd have to wait another 11 min before I can do anything. Is there any way to shorten this time? 
3. This issue wasn't present when I make recordings on my iPhone/Safari. There, I pressed "stop" and got the play back + tagging button right away. 

@ichimura-a, can you check whether this fixes the upload recording issues you mentioned? Once you've confirmed, we can push this fix to the production site. THanks again for fixing this. Can you also pass along info about why the converting times are so long on PC/Chrome and the fix for restoring the older recordings? Thanks!

**Comment by ichimura-a** [comment]
All recordings have posted, the new fix has fixed the recording issues I had.

**Comment by jkhartshorne** [comment]
@ythuang123 regarding speed of processing, see https://github.com/jkhartshorne/KidTalkIssues/issues/33 and https://github.com/alexchippendale/KidTalkRemainingTasks/issues/19

**Comment by alexchippendale** [comment]
@ythuang123 @ichimura-a Thanks for testing!

**Comment by jkhartshorne** [comment]
I"m going to go ahead and close this.

**Comment by ythuang123** [comment]
Hi folks -- I've been testing out Phase 2 on the production site. Overall, it's great. Love the fast processing, fun icons, beautiful layout. BUT... I just encountered this "stuck clip" error -- see below. It was a short clip (2-3 minutes). And I had made a much longer one right before that uploaded fine. I'm using my iPhone SE (version iOS 13.5.1) on Safari (latest?). 

![2020-09-04_21-01-21_000](https://user-images.githubusercontent.com/68764650/92294418-1af94580-eefa-11ea-8fc8-7fcb832fd6ca.png)
![2020-09-04_21-06-35_000](https://user-images.githubusercontent.com/68764650/92294419-1c2a7280-eefa-11ea-89f4-7e9879ac14ad.png)

**Comment by jkhartshorne** [comment]
@lorenachipstudio It's ba-ack!

**Comment by SecondStreetDevelopment** [comment]
Hi @ythuang123, I'm pretty sure this is happening for a different reason than previously.  I'm looking into it now.

**Comment by SecondStreetDevelopment** [comment]
@ythuang123, I manually changed the database record for this recording.  Take a look at the recording when you get a chance and let me know if it's working now.

**Comment by ythuang123** [comment]
@SecondStreetDevelopment -- perfect, it works! The new clip is unstuck. Thanks!!

**Comment by SecondStreetDevelopment** [comment]
@ythuang123, no problem.  I was able to manually modify that database record but I haven't been able to isolate the root cause of this issue yet.  If it happens again please let me know.  The screen captures are very helpful.  Also, if you know the day and approximate time you experienced the issue that can help me find it faster.

**Comment by ythuang123** [comment]
@SecondStreetDevelopment -- hello! Same deal as before. The "stuck clip" error was on the production site (9/9, around 8:34pm on the photo) -- see below. It was another short clip (2-3 minutes). I'm using my iPhone SE (version iOS 13.5.1) on Safari (latest?).
![2020-09-09_20-34-38_000](https://user-images.githubusercontent.com/68764650/92672470-bf0e3280-f2e6-11ea-951b-47f296c37576.png)
![2020-09-09_20-39-40_000](https://user-images.githubusercontent.com/68764650/92672473-c03f5f80-f2e6-11ea-9806-3ddb7d3479d8.png)

**Comment by ythuang123** [comment]
@SecondStreetDevelopment  -- These two are from yesterday night (9/10, timestamp on the photos). Same deal as before. The "stuck clip" error was on the production site -- see below. They were short clips (2-4 minutes). I'm using my iPhone SE (version iOS 13.7) on Safari (13). Any thoughts about what's going on? Thanks for your help!

![2020-09-10_20-57-16_000](https://user-images.githubusercontent.com/68764650/92928244-d0e9f580-f40c-11ea-976d-504def71710c.png)
![2020-09-10_20-58-01_000](https://user-images.githubusercontent.com/68764650/92928252-d2b3b900-f40c-11ea-93fb-8617f5cc7cb1.png)
![2020-09-10_21-02-08_000](https://user-images.githubusercontent.com/68764650/92928254-d34c4f80-f40c-11ea-95a4-82ae12212f59.png)

**Comment by SecondStreetDevelopment** [comment]
@ythuang123, I just manually fixed those recordings. I think I have identified the source of the issue with these recordings. I'm working on a fix

**Comment by ythuang123** [comment]
@SecondStreetDevelopment -- got it, thanks! They are all unstuck (woo-hoo!). I'll post again if it happens again. LMK if you need recordings of particular types (e.g., length, platform, browser) to test out hypotheses. I can supply.

**Comment by ythuang123** [comment]
@SecondStreetDevelopment -- two more stuck recordings from yesterday (time stamp on photos). I haven't been able to make an unstuck recording since 9/4. Do you have a sense of the cause or scope of this problem?

![2020-09-13_20-37-56_000](https://user-images.githubusercontent.com/68764650/93105556-3ba16800-f67d-11ea-9198-384c690b4576.png)
![2020-09-13_20-38-14_000](https://user-images.githubusercontent.com/68764650/93105557-3ba16800-f67d-11ea-863f-5d82b5ab2740.png)
![2020-09-13_20-38-24_000](https://user-images.githubusercontent.com/68764650/93105558-3ba16800-f67d-11ea-9571-47defbc1f9de.png)

**Comment by jkhartshorne** [comment]
@lorenachipstudio  Any progress?

**Comment by lorenachipstudio** [comment]
@jkhartshorne We're working on a temporary patch while we figure this out. We'll update you on here as soon as this is ready.

**Comment by lorenachipstudio** [comment]
@jkhartshorne We just deployed a patch that should stop the recordings from appearing stuck and will also "unstick" the recordings from the last few days. We're working on fixing the root cause right now.

**Comment by SecondStreetDevelopment** [comment]
We have identified the root cause and deployed a fix to production just now.

**Comment by SecondStreetDevelopment** [comment]
I'm guessing recordings made over the weekend will be grayed out due to this issue.  I'm looking for a way to bulk process those recordings and make them available now.

**Comment by jkhartshorne** [comment]
Thanks!

**Comment by ythuang123** [comment]
@SecondStreetDevelopment -- it worked! The two recordings from the weekend are unstuck. I made two more and they posted just fine. Thanks for tackling this so quickly.

**Comment by jkhartshorne** [comment]
Mine are unstuck as well!
