### ISSUE TITLE
No avatar for comments?

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#27]
**What I expect**
Some sort of icon next to my comment

**What I see**
Blank circle.

**Who am I?**
Chrome Version 84.0.4147.105
MacBook Air - 10.15.6

![Screen Shot 2020-08-05 at 2 32 20 PM](https://user-images.githubusercontent.com/6118115/89450762-112cc880-d729-11ea-9b21-622f2cd621ba.png)

**Comment by lorenachipstudio** [comment]
@jkhartshorne we'll take a look

**Comment by lorenachipstudio** [comment]
@jkhartshorne Currently if you do not have a selected avatar at the time of the comment you will see a blank circle.

You can just go to the Settings page to see if you've selected an avatar. Once selected, future comments will show their avatar instead of a blank circle.

**Comment by jkhartshorne** [comment]
@lorenachipstudio - I just selected an avatar. The comment did not update. If we're not going to have it update, can it at least be the circle with the initial in it to start with?

**Comment by lorenachipstudio** [comment]
@jkhartshorne We've updated staging to now show the first name of the commenter under their avatar and changed the blank circle to a better looking generic grey stand in avatar. It's possible some comment submissions on staging prior to this update may not include the name (though most will), but going forward even if a new user does not have a selected avatar and they comment, they will at least see their name next to the comment and the generic avatar rather than a blank circle.

**Comment by jkhartshorne** [comment]
Unfortunately, I cannot yet test this functionality. See https://github.com/jkhartshorne/KidTalkIssues/issues/31

**Comment by alexchippendale** [comment]
@jkhartshorne Should be able to test what @lorenachipstudio wrote above now. Button from #31 should be unstuck, thanks.

**Comment by jkhartshorne** [comment]
Looks good.
