### ISSUE TITLE
"Children shared with me" lists users, not children

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#29]
As you can see in this screenshot, "Children Shared With Me" lists the user, not the child. BTW, the user is the account shared with, not the account that did the sharing. So all I know is that I have access to ... myself?

Also, what's "Actions"?

- MacOS 10.15.6
- Chrome 84.0.4147.105

![Screen Shot 2020-08-09 at 9 32 09 AM](https://user-images.githubusercontent.com/6118115/89733425-69aedf00-da23-11ea-8c14-92bac35c62d2.png)

**Comment by jkhartshorne** [comment]
@lorenachipstudio just making sure you saw this.

**Comment by lorenachipstudio** [comment]
@jkhartshorne Yes- i reported this to our dev team!

**Comment by alexchippendale** [comment]
@jkhartshorne Yes, it looks like it's pulling in the correct sharing invitation but using the adult's name instead of the child's. We are working on having it say "Child" or "Child Name" instead of "User", and using the actual child's name instead of the user that was shared with (which in this case is just that logged in user!). We'll let you know when it is updated, thanks.

**Comment by alexchippendale** [comment]
@jkhartshorne This should now be fixed on staging, please confirm when you get a chance!

**Comment by jkhartshorne** [comment]
Yep!
