### ISSUE TITLE
Filtering by "only clips with no label"

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#45]
**What I expect:** 
Everything that is unlabeled to appear when I select "only clips with no label"

**What happens:**
Only some of them appear.

Before: 
![Screen Shot 2020-08-31 at 4 17 54 PM](https://user-images.githubusercontent.com/6118115/91764583-916a1080-eba5-11ea-8a8b-1f36d4c39a20.png)

After:

![Screen Shot 2020-08-31 at 4 18 00 PM](https://user-images.githubusercontent.com/6118115/91764597-962ec480-eba5-11ea-8880-43d5447c53a0.png)

**Comment by lorenachipstudio** [comment]
@jkhartshorne We'll take a look with the team

**Comment by alexchippendale** [comment]
@jkhartshorne Just to make sure: In the before picture, are you showing this because there are tiles with the "?" icon that don't appear in the bottom one? The "?" appears if there is no selected icon, not based on if there is a label aka a description or transcription. 

Also, roughly how many tiles / recordings do you have? This could help us in debugging. Thanks!

**Comment by jkhartshorne** [comment]
OH, yah. I forgot that blank doesn't mean there isn't a description.
