### ISSUE TITLE
Say What Audio Clips Stop Playing 

### ISSUE THREAD

**Issue by jmnolasco** [jkhartshorne/KidTalkIssues#7]
After about 5 clips, it doesn't refresh with new audio clips to transcribe. 

It'll repeat the last one presented, and then gets stuck from there.

Seen on iPhone XR, Safari browser.

**Comment by lorenachipstudio** [comment]
@jmnolasco thanks- we'll take a look at this and get back to you with updates. 

Lorena

**Comment by lorenachipstudio** [comment]
@jmnolasco this should be fixed in staging- can you confirm?

**Comment by jmnolasco** [comment]
I tried out Say What & now i'm getting something strange like background noise for the audio. When I press play, I heard background noise and when I "submit guess" it gives me an actual transcription. I tried this in staging.

I also tried it in the actual app, and didn't encounter this issue anymore so I'm not sure if it's actually my phone

**Comment by jmnolasco** [comment]
Thank you so much for your work on this!

**Comment by alexchippendale** [comment]
@jmnolasco Thanks for testing! I believe you are hearing test clips on staging, some of which are given transcriptions as the devs do testing even if it's just a background noise. This week we are working on removing test clips so that it's clear the difference between a bug in the code and just a bunch of test clips. Let us know if that makes sense!
