### ISSUE TITLE
Say What: Audio doesn't stop playing

### ISSUE THREAD

**Issue by ichimura-a** [jkhartshorne/KidTalkIssues#9]
iPhone 7 / Safari / iOS 13.5.1
The audio clip plays and then goes silent, yet the pause button remains and never turns into a play button. A transcription can be entered but can't be submitted. The next "Say What?" clip can't be played.

**Comment by koppen152** [comment]
This just happened to me on iPhone 7 / Safari / iOS 13.6

**Comment by koppen152** [comment]
just encountered this on Windows 10/laptop/Chrome 83

maybe worth noting that my laptop is terrible and really slow at everything.

**Comment by lorenachipstudio** [comment]
@koppen152 @koppen152 Thank you for reporting this issue- we'll take a look and provide an update shortly. 

Lorena

**Comment by ythuang123** [comment]
I've encountered this bug too. 

Browser / Chrome

OS / Window 10 Enterprise v. 1909 (OS build 18563.959)

device / ThinkPad X1 Carbon 4G

**Comment by lorenachipstudio** [comment]
@ythuang123 @koppen152 @ichimura-a this should be resolved on staging now. Can you confirm when you get a chance?

**Comment by koppen152** [comment]
@lorenachipstudio this is fixed for me. Thanks!

**Comment by ythuang123** [comment]
@lorenachipstudio -- The audio stops playing now, but it's _only_ played the same audio clip (sounds like a door shutting) after 10+ plays. So I can't tell if this issue is really fixed because it can now seamless plays a variety of audio without stop or whether the set of audio clips have been narrowed to a single one than can be played without issue. Would it be possible to add in other audio clips so that we can fully test this out? Or is the fact that it's the same audio clip a different bug to report?

**Comment by ichimura-a** [comment]
@lorenachipstudio This is also fixed for me.

**Comment by alexchippendale** [comment]
Thanks for testing @ythuang123 @koppen152 @ichimura-a!

@ythuang123 are you testing on staging or production?

**Comment by ythuang123** [comment]
Staging -- I just checked it again, and still getting the same clip 10+ times. Again, I can't tell if this is a real bug or just that the fact that there aren't many recordings to draw from for "Say What." Here's [an audio recording of what I hear after the mouse clicks](https://drive.google.com/file/d/1wy6akL4U9di5p-HQJ444Twv7UIfqHH4J/view?usp=sharing).

**Comment by alexchippendale** [comment]
@ythuang123 I see. I believe the issue you're referring to there is issue #7 Say What Clips Stop Playing. Take a look at that one, but the door shutting sound or background noise sounds sound like the test clips I've heard. We will be going through this week and removing test clips from staging. There is an admin portal for production where only good real clips can be selected, I will go over this with the dev team and see if we can set up something similar for staging so that test clips do not come across as a bug in the code.

**Comment by ythuang123** [comment]
@alexchippendale -- got it, and so after the test clips are removed, we'll hear a variety of sound clips for "Say What" (not just the same one over and over again)?

**Comment by alexchippendale** [comment]
@ythuang123 Yes, we will also activate clips for Say What on staging which are good quality. Right now you're basically hearing 10 very similar sounding background noise clips from devs since clips from our accounts on staging are currently the only ones it pools from which we used for internal testing. We will change this pool to show actual clips from people who have been testing real clips on staging. We'll let you know when it is updated!

**Comment by alexchippendale** [comment]
@ythuang123 We've removed the test clips from the pool so this should be resolved on staging now. There are only 5 or 6 clips that fit the criteria of Say What? right now on staging. These are clips made by people testing staging (but not the devs) and there aren't a lot at the moment so you should expect to hear repeats sometimes, though you should no longer hear the background noise sounds (unless people start uploading sounds like that). As more public short clips are added on staging, the pool will grow. Can you confirm that the background noises are now gone on staging and you can hear clips of people's voices? Thanks!

**Comment by ythuang123** [comment]
@alexchippendale -- this is resolved for me, thanks! I hear many clips of @parkerrobbins's recitation of the Universal declaration of human rights. :)
